# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-26 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, upload_to=b'blog/article/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='blogad',
            name='img_url',
            field=models.ImageField(upload_to=b'blog/ad/%Y/%m'),
        ),
    ]
