# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-26 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170726_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='propic',
            name='index',
            field=models.IntegerField(default=999, verbose_name='\u663e\u793a\u987a\u5e8f'),
        ),
        migrations.AlterField(
            model_name='propic',
            name='img_url',
            field=models.ImageField(upload_to=b'blog/ProPic/%Y/%m'),
        ),
    ]
