# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-27 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170726_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='img_url',
            field=models.ImageField(blank=True, upload_to=b'blog/video/%Y/%m'),
        ),
    ]
