# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-25 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xphone', '0002_auto_20170724_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbars',
            name='english',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
