# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-28 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xphone', '0003_navbars_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default=b'avatar/default', max_length=200, null=True, upload_to=b'avatar/%Y/%m', verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\xa4\xb4\xe5\x83\x8f')),
                ('name', models.CharField(max_length=30, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=11, null=True)),
                ('addr', models.CharField(blank=True, max_length=30, null=True)),
                ('regDate', models.DateTimeField()),
                ('isDelete', models.BooleanField(default=False)),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
    ]
