# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-28 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xphone', '0004_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbars',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6307\u5411\u5730\u5740'),
        ),
    ]
