# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-24 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=11, null=True)),
                ('addr', models.CharField(blank=True, max_length=30, null=True)),
                ('regDate', models.DateTimeField()),
                ('isDelete', models.BooleanField(default=False)),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
    ]
