# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-24 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u5e7f\u544a\u63cf\u8ff0')),
                ('img_url', models.ImageField(upload_to=b'uploads/')),
                ('AdName', models.CharField(max_length=20)),
                ('index', models.IntegerField(default=999)),
            ],
            options={
                'verbose_name': '\u5546\u57ce\u5e7f\u544a',
                'verbose_name_plural': '\u5546\u57ce\u5e7f\u544a',
            },
        ),
        migrations.CreateModel(
            name='Navtags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagName', models.CharField(max_length=20)),
                ('TagImg', models.ImageField(upload_to=b'uploads/')),
            ],
            options={
                'verbose_name': '\u5bfc\u822a\u6807\u7b7e',
                'verbose_name_plural': '\u5bfc\u822a\u6807\u7b7e',
            },
        ),
        migrations.CreateModel(
            name='PhoneArg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('arg_desc', models.CharField(max_length=200)),
                ('img_url', models.ImageField(upload_to=b'uploads/')),
            ],
            options={
                'verbose_name': '\u624b\u673a\u53c2\u6570',
                'verbose_name_plural': '\u624b\u673a\u53c2\u6570',
            },
        ),
        migrations.CreateModel(
            name='ServerContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to=b'uploads/', verbose_name='\u56fe\u7247')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u9009\u9879',
                'verbose_name_plural': '\u670d\u52a1\u9009\u9879',
            },
        ),
        migrations.CreateModel(
            name='ShopSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleName', models.CharField(max_length=30)),
                ('saleDese', models.CharField(max_length=30)),
                ('salePrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saleImg', models.ImageField(upload_to=b'uploads/')),
            ],
            options={
                'verbose_name': '\u5546\u57ce\u9996\u9875\u5546\u54c1',
                'verbose_name_plural': '\u5546\u57ce\u9996\u9875\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='TagGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodImg', models.ImageField(upload_to=b'uploads/')),
                ('goodName', models.CharField(max_length=20)),
                ('goodPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3, max_length=1, verbose_name='\u6298\u6263')),
                ('Navtags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Navtags', verbose_name=b'\xe5\xaf\xbc\xe8\x88\xaa\xe6\xa0\x87\xe7\xad\xbe')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e\u8be6\u60c5',
                'verbose_name_plural': '\u6807\u7b7e\u8be6\u60c5',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='Navtags_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Navtags'),
        ),
    ]
