# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-24 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsales',
            name='index',
            field=models.IntegerField(default=999, verbose_name='\u663e\u793a\u987a\u5e8f'),
        ),
    ]
