# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-24 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopsales_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='img_url',
            field=models.ImageField(upload_to=b'shop/ad/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='navtags',
            name='TagImg',
            field=models.ImageField(upload_to=b'shop/navtags/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='phonearg',
            name='img_url',
            field=models.ImageField(upload_to=b'shop/phone/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='servercontent',
            name='img_url',
            field=models.ImageField(upload_to=b'shop/server/%Y/%m', verbose_name='\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='shopsales',
            name='saleImg',
            field=models.ImageField(upload_to=b'shop/sales/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='taggoods',
            name='goodImg',
            field=models.ImageField(upload_to=b'shop/%Y/%m'),
        ),
    ]
