# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-28 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '\u89c4\u683c\u53c2\u6570',
                'verbose_name_plural': '\u89c4\u683c\u53c2\u6570',
            },
        ),
        migrations.CreateModel(
            name='Prob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '\u5e38\u89c1\u95ee\u9898',
                'verbose_name_plural': '\u5e38\u89c1\u95ee\u9898',
            },
        ),
        migrations.CreateModel(
            name='Product_desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to=b'shop/product_desc/%Y/%m')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u8be6\u60c5',
                'verbose_name_plural': '\u5546\u54c1\u8be6\u60c5',
            },
        ),
    ]
