# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-28 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20170728_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='arg',
            name='index',
            field=models.IntegerField(default=999, verbose_name=b'\xe6\x8e\x92\xe5\xba\x8f'),
        ),
        migrations.AddField(
            model_name='prob',
            name='index',
            field=models.IntegerField(default=999, verbose_name=b'\xe6\x8e\x92\xe5\xba\x8f'),
        ),
        migrations.AddField(
            model_name='product_desc',
            name='index',
            field=models.IntegerField(default=999, verbose_name=b'\xe6\x8e\x92\xe5\xba\x8f'),
        ),
    ]
