# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-28 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20170728_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prob',
            name='desc',
            field=models.CharField(max_length=2000),
        ),
    ]
